
server:
  port: 80
spring:
  profiles:
    active: dev

  sql:
    init:
      platform: postgres
      mode: always
  jpa:
    defer-datasource-initialization: true
#    database-platform: postgres
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      format_sql: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/ajo_db
    driverClassName: org.postgresql.Driver
    username:
    password:
